### ISSUE TITLE
Phase error in latest sponge

### ISSUE THREAD

**Issue by clienthax** [codeHusky/HuskyUI-Plugin#20] opened 2018-02-15 22:11 UTC
https://pastebin.ubuntu.com/p/CQb5GJ4D2j/

**Comment by codeHusky** [comment] 2018-02-16 16:58
oh fun.

**Comment by codeHusky** [comment] 2018-02-16 17:02
seems like a sponge bug tbh, i don't know why I wouldn't be able to close an inventory during an inventory event.

**Comment by clienthax** [comment] 2018-02-20 04:42
@codeHusky If you figure what exactly is causing it just raise it on the sponge tracker :)

**Comment by codeHusky** [comment] 2018-03-21 05:27
Seems to be no longer an issue. I'm closing this unless you have been able to reproduce it @clienthax

**Closed by codeHusky** 2018-03-21 05:27 UTC
